### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by thijstriemstra** [alaudet/hcsr04sensor#15]
A quick search in this library shows 2 `time.sleep` calls, blocking my app. Would be nice to have async support, e.g. `asyncio.sleep`.

**Comment by thijstriemstra** [comment]
ps. thanks for the wealth of info in the readme, wish I would've found this library sooner.

**Comment by alaudet** [comment]
Hello, have you actually tested it?

**Comment by thijstriemstra** [comment]
not yet, about to. :)

**Comment by thijstriemstra** [comment]
i'm not going to install from pypi since it pins RPi.GPIO to an outdated version. Any reason for this?

**Comment by thijstriemstra** [comment]
Tested and works great. My previous script took over 2 seconds (with 2 seconds 'warmup time' for the sensor) but it had quite a few misreadings. Your strategy of 11 samples is much better. So I'm not bothered by the 1.1 second time.sleep at this point, feel free to close this issue.

Unfortunately the sensor itself seems quite sensitive to moisture and after a few days attached to the top of a water tank it starts to return a incorrect value. Taking the sensor out and heating it for a minute will fix this but it's not a good solution, so I ordered a JSN-SR04T and see what that does: https://www.ebay.com/itm/JSN-SR04T-Ultrasonic-Module-Distance-Measuring-Transducer-Sensor-Waterproof-Y4R2/323976533195

**Comment by alaudet** [comment]
About the pinning, I really need to keep on top of that.  There was once an update to RPi.GPIO that broke the library.  Since I have decided to only change the pinned version if I do updates and have tested it to work.  I will take a look when I have some time to ensure the latest version of RPi.GPIO  doesn't break anything and I will pin it to the latest.

As for the HCSR04 they are cheap sensors that don't like moisture.  You need the JSN-SR04T.  I have tested it and it works fine.

**Comment by thijstriemstra** [comment]
> As for the HCSR04 they are cheap sensors that don't like moisture. You need the JSN-SR04T. I have tested it and it works fine.

Maybe this would be a good piece of advice for in the readme. Saves people some weeks of extra waiting for parts from ebay ;)
